modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="contentstudio"
version="${file.jarVersion}"
displayName="Content Studio"
authors="XYAT"
description='''
Visual content authoring tools for recipes, loot, villager trades, and item tooltips.
'''

[[dependencies.contentstudio]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.contentstudio]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.contentstudio]]
modId="kineticcore"
mandatory=true
versionRange="[26.9.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.contentstudio]]
modId="jei"
mandatory=false
versionRange="[15.20,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.contentstudio]]
modId="emi"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.contentstudio]]
modId="roughlyenoughitems"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
